# bbdd-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: servicio-{{ .Release.Name }}-bbdd
  namespace: "{{ .Values.namespace }}"
spec:
  selector:  
    app: wp-mysql
  ports:  # esta é a parte de especificación propia
  - protocol: TCP
    port: 3306
    targetPort: 3306
