apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    tipo: "config"        
data:
  MYSQL_HOST: service-{{ .Release.Name }}-mysql
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}

 {{ .Values.env | toYaml | nindent 2}}
